from Code import Util
from Code.Odt import XML


class Settings(XML.XML):
    def __init__(self):
        XML.XML.__init__(self, "office:document-settings")
        self.add_param("xmlns:office", "urn:oasis:names:tc:opendocument:xmlns:office:1.0")
        self.add_param("xmlns:ooo", "http://openoffice.org/2004/office")
        self.add_param("xmlns:xlink", "http://www.w3.org/1999/xlink")
        self.add_param("xmlns:config", "urn:oasis:names:tc:opendocument:xmlns:config:1.0")
        self.add_param("office:version", "1.3")
        element1 = XML.Element("office:settings")
        self.add_content(element1)
        element2 = XML.Element("config:config-item-set")
        element2.add_param("config:name", "ooo:view-settings")
        element1.add_content(element2)
        element3 = XML.Element("config:config-item")
        element3.add_param("config:name", "ViewAreaTop")
        element3.add_param("config:type", "long")
        element2.add_content(element3)
        element3.set_value("0")
        element4 = XML.Element("config:config-item")
        element4.add_param("config:name", "ViewAreaLeft")
        element4.add_param("config:type", "long")
        element2.add_content(element4)
        element4.set_value("0")
        element5 = XML.Element("config:config-item")
        element5.add_param("config:name", "ViewAreaWidth")
        element5.add_param("config:type", "long")
        element2.add_content(element5)
        element5.set_value("43155")
        element6 = XML.Element("config:config-item")
        element6.add_param("config:name", "ViewAreaHeight")
        element6.add_param("config:type", "long")
        element2.add_content(element6)
        element6.set_value("26143")
        element7 = XML.Element("config:config-item")
        element7.add_param("config:name", "ShowRedlineChanges")
        element7.add_param("config:type", "boolean")
        element2.add_content(element7)
        element7.set_value("false")
        element8 = XML.Element("config:config-item")
        element8.add_param("config:name", "InBrowseMode")
        element8.add_param("config:type", "boolean")
        element2.add_content(element8)
        element8.set_value("false")
        element9 = XML.Element("config:config-item-map-indexed")
        element9.add_param("config:name", "Views")
        element2.add_content(element9)
        element10 = XML.Element("config:config-item-map-entry")
        element9.add_content(element10)
        element11 = XML.Element("config:config-item")
        element11.add_param("config:name", "ViewId")
        element11.add_param("config:type", "string")
        element10.add_content(element11)
        element11.set_value("view2")
        element12 = XML.Element("config:config-item")
        element12.add_param("config:name", "ViewLeft")
        element12.add_param("config:type", "long")
        element10.add_content(element12)
        element12.set_value("13077")
        element13 = XML.Element("config:config-item")
        element13.add_param("config:name", "ViewTop")
        element13.add_param("config:type", "long")
        element10.add_content(element13)
        element13.set_value("2501")
        element14 = XML.Element("config:config-item")
        element14.add_param("config:name", "VisibleLeft")
        element14.add_param("config:type", "long")
        element10.add_content(element14)
        element14.set_value("0")
        element15 = XML.Element("config:config-item")
        element15.add_param("config:name", "VisibleTop")
        element15.add_param("config:type", "long")
        element10.add_content(element15)
        element15.set_value("0")
        element16 = XML.Element("config:config-item")
        element16.add_param("config:name", "VisibleRight")
        element16.add_param("config:type", "long")
        element10.add_content(element16)
        element16.set_value("43154")
        element17 = XML.Element("config:config-item")
        element17.add_param("config:name", "VisibleBottom")
        element17.add_param("config:type", "long")
        element10.add_content(element17)
        element17.set_value("26141")
        element18 = XML.Element("config:config-item")
        element18.add_param("config:name", "ZoomType")
        element18.add_param("config:type", "short")
        element10.add_content(element18)
        element18.set_value("0")
        element19 = XML.Element("config:config-item")
        element19.add_param("config:name", "ViewLayoutColumns")
        element19.add_param("config:type", "short")
        element10.add_content(element19)
        element19.set_value("0")
        element20 = XML.Element("config:config-item")
        element20.add_param("config:name", "ViewLayoutBookMode")
        element20.add_param("config:type", "boolean")
        element10.add_content(element20)
        element20.set_value("false")
        element21 = XML.Element("config:config-item")
        element21.add_param("config:name", "ZoomFactor")
        element21.add_param("config:type", "short")
        element10.add_content(element21)
        element21.set_value("100")
        element22 = XML.Element("config:config-item")
        element22.add_param("config:name", "IsSelectedFrame")
        element22.add_param("config:type", "boolean")
        element10.add_content(element22)
        element22.set_value("false")
        element23 = XML.Element("config:config-item")
        element23.add_param("config:name", "KeepRatio")
        element23.add_param("config:type", "boolean")
        element10.add_content(element23)
        element23.set_value("false")
        element24 = XML.Element("config:config-item")
        element24.add_param("config:name", "AnchoredTextOverflowLegacy")
        element24.add_param("config:type", "boolean")
        element10.add_content(element24)
        element24.set_value("false")
        element25 = XML.Element("config:config-item-set")
        element25.add_param("config:name", "ooo:configuration-settings")
        element1.add_content(element25)
        element26 = XML.Element("config:config-item")
        element26.add_param("config:name", "ProtectForm")
        element26.add_param("config:type", "boolean")
        element25.add_content(element26)
        element26.set_value("false")
        element27 = XML.Element("config:config-item")
        element27.add_param("config:name", "PrinterName")
        element27.add_param("config:type", "string")
        element25.add_content(element27)
        element28 = XML.Element("config:config-item")
        element28.add_param("config:name", "EmbeddedDatabaseName")
        element28.add_param("config:type", "string")
        element25.add_content(element28)
        element29 = XML.Element("config:config-item")
        element29.add_param("config:name", "CurrentDatabaseDataSource")
        element29.add_param("config:type", "string")
        element25.add_content(element29)
        element30 = XML.Element("config:config-item")
        element30.add_param("config:name", "LinkUpdateMode")
        element30.add_param("config:type", "short")
        element25.add_content(element30)
        element30.set_value("1")
        element31 = XML.Element("config:config-item")
        element31.add_param("config:name", "AddParaTableSpacingAtStart")
        element31.add_param("config:type", "boolean")
        element25.add_content(element31)
        element31.set_value("false")
        element32 = XML.Element("config:config-item")
        element32.add_param("config:name", "FloattableNomargins")
        element32.add_param("config:type", "boolean")
        element25.add_content(element32)
        element32.set_value("false")
        element33 = XML.Element("config:config-item")
        element33.add_param("config:name", "UnbreakableNumberings")
        element33.add_param("config:type", "boolean")
        element25.add_content(element33)
        element33.set_value("false")
        element34 = XML.Element("config:config-item")
        element34.add_param("config:name", "FieldAutoUpdate")
        element34.add_param("config:type", "boolean")
        element25.add_content(element34)
        element34.set_value("false")
        element35 = XML.Element("config:config-item")
        element35.add_param("config:name", "AddVerticalFrameOffsets")
        element35.add_param("config:type", "boolean")
        element25.add_content(element35)
        element35.set_value("false")
        element36 = XML.Element("config:config-item")
        element36.add_param("config:name", "BackgroundParaOverDrawings")
        element36.add_param("config:type", "boolean")
        element25.add_content(element36)
        element36.set_value("false")
        element37 = XML.Element("config:config-item")
        element37.add_param("config:name", "AddParaTableSpacing")
        element37.add_param("config:type", "boolean")
        element25.add_content(element37)
        element37.set_value("false")
        element38 = XML.Element("config:config-item")
        element38.add_param("config:name", "ChartAutoUpdate")
        element38.add_param("config:type", "boolean")
        element25.add_content(element38)
        element38.set_value("false")
        element39 = XML.Element("config:config-item")
        element39.add_param("config:name", "CurrentDatabaseCommand")
        element39.add_param("config:type", "string")
        element25.add_content(element39)
        element40 = XML.Element("config:config-item")
        element40.add_param("config:name", "PrinterSetup")
        element40.add_param("config:type", "base64Binary")
        element25.add_content(element40)
        element41 = XML.Element("config:config-item")
        element41.add_param("config:name", "AlignTabStopPosition")
        element41.add_param("config:type", "boolean")
        element25.add_content(element41)
        element41.set_value("false")
        element42 = XML.Element("config:config-item")
        element42.add_param("config:name", "PrinterPaperFromSetup")
        element42.add_param("config:type", "boolean")
        element25.add_content(element42)
        element42.set_value("false")
        element43 = XML.Element("config:config-item")
        element43.add_param("config:name", "IsKernAsianPunctuation")
        element43.add_param("config:type", "boolean")
        element25.add_content(element43)
        element43.set_value("false")
        element44 = XML.Element("config:config-item")
        element44.add_param("config:name", "CharacterCompressionType")
        element44.add_param("config:type", "short")
        element25.add_content(element44)
        element44.set_value("0")
        element45 = XML.Element("config:config-item")
        element45.add_param("config:name", "ApplyUserData")
        element45.add_param("config:type", "boolean")
        element25.add_content(element45)
        element45.set_value("false")
        element46 = XML.Element("config:config-item")
        element46.add_param("config:name", "DoNotJustifyLinesWithManualBreak")
        element46.add_param("config:type", "boolean")
        element25.add_content(element46)
        element46.set_value("false")
        element47 = XML.Element("config:config-item")
        element47.add_param("config:name", "SaveThumbnail")
        element47.add_param("config:type", "boolean")
        element25.add_content(element47)
        element47.set_value("false")
        element48 = XML.Element("config:config-item")
        element48.add_param("config:name", "SaveGlobalDocumentLinks")
        element48.add_param("config:type", "boolean")
        element25.add_content(element48)
        element48.set_value("false")
        element49 = XML.Element("config:config-item")
        element49.add_param("config:name", "SmallCapsPercentage66")
        element49.add_param("config:type", "boolean")
        element25.add_content(element49)
        element49.set_value("false")
        element50 = XML.Element("config:config-item")
        element50.add_param("config:name", "CurrentDatabaseCommandType")
        element50.add_param("config:type", "int")
        element25.add_content(element50)
        element50.set_value("0")
        element51 = XML.Element("config:config-item")
        element51.add_param("config:name", "SaveVersionOnClose")
        element51.add_param("config:type", "boolean")
        element25.add_content(element51)
        element51.set_value("false")
        element52 = XML.Element("config:config-item")
        element52.add_param("config:name", "UpdateFromTemplate")
        element52.add_param("config:type", "boolean")
        element25.add_content(element52)
        element52.set_value("false")
        element53 = XML.Element("config:config-item")
        element53.add_param("config:name", "DoNotCaptureDrawObjsOnPage")
        element53.add_param("config:type", "boolean")
        element25.add_content(element53)
        element53.set_value("false")
        element54 = XML.Element("config:config-item")
        element54.add_param("config:name", "UseFormerObjectPositioning")
        element54.add_param("config:type", "boolean")
        element25.add_content(element54)
        element54.set_value("false")
        element55 = XML.Element("config:config-item")
        element55.add_param("config:name", "PrintSingleJobs")
        element55.add_param("config:type", "boolean")
        element25.add_content(element55)
        element55.set_value("false")
        element56 = XML.Element("config:config-item")
        element56.add_param("config:name", "EmbedSystemFonts")
        element56.add_param("config:type", "boolean")
        element25.add_content(element56)
        element56.set_value("false")
        element57 = XML.Element("config:config-item")
        element57.add_param("config:name", "PrinterIndependentLayout")
        element57.add_param("config:type", "string")
        element25.add_content(element57)
        element57.set_value("high-resolution")
        element58 = XML.Element("config:config-item")
        element58.add_param("config:name", "IsLabelDocument")
        element58.add_param("config:type", "boolean")
        element25.add_content(element58)
        element58.set_value("false")
        element59 = XML.Element("config:config-item")
        element59.add_param("config:name", "AddFrameOffsets")
        element59.add_param("config:type", "boolean")
        element25.add_content(element59)
        element59.set_value("false")
        element60 = XML.Element("config:config-item")
        element60.add_param("config:name", "AddExternalLeading")
        element60.add_param("config:type", "boolean")
        element25.add_content(element60)
        element60.set_value("false")
        element61 = XML.Element("config:config-item")
        element61.add_param("config:name", "MsWordCompMinLineHeightByFly")
        element61.add_param("config:type", "boolean")
        element25.add_content(element61)
        element61.set_value("false")
        element62 = XML.Element("config:config-item")
        element62.add_param("config:name", "UseOldNumbering")
        element62.add_param("config:type", "boolean")
        element25.add_content(element62)
        element62.set_value("false")
        element63 = XML.Element("config:config-item")
        element63.add_param("config:name", "OutlineLevelYieldsNumbering")
        element63.add_param("config:type", "boolean")
        element25.add_content(element63)
        element63.set_value("false")
        element64 = XML.Element("config:config-item")
        element64.add_param("config:name", "DoNotResetParaAttrsForNumFont")
        element64.add_param("config:type", "boolean")
        element25.add_content(element64)
        element64.set_value("false")
        element65 = XML.Element("config:config-item")
        element65.add_param("config:name", "IgnoreFirstLineIndentInNumbering")
        element65.add_param("config:type", "boolean")
        element25.add_content(element65)
        element65.set_value("false")
        element66 = XML.Element("config:config-item")
        element66.add_param("config:name", "AllowPrintJobCancel")
        element66.add_param("config:type", "boolean")
        element25.add_content(element66)
        element66.set_value("false")
        element67 = XML.Element("config:config-item")
        element67.add_param("config:name", "UseFormerLineSpacing")
        element67.add_param("config:type", "boolean")
        element25.add_content(element67)
        element67.set_value("false")
        element68 = XML.Element("config:config-item")
        element68.add_param("config:name", "AddParaSpacingToTableCells")
        element68.add_param("config:type", "boolean")
        element25.add_content(element68)
        element68.set_value("false")
        element69 = XML.Element("config:config-item")
        element69.add_param("config:name", "AddParaLineSpacingToTableCells")
        element69.add_param("config:type", "boolean")
        element25.add_content(element69)
        element69.set_value("false")
        element70 = XML.Element("config:config-item")
        element70.add_param("config:name", "UseFormerTextWrapping")
        element70.add_param("config:type", "boolean")
        element25.add_content(element70)
        element70.set_value("false")
        element71 = XML.Element("config:config-item")
        element71.add_param("config:name", "RedlineProtectionKey")
        element71.add_param("config:type", "base64Binary")
        element25.add_content(element71)
        element72 = XML.Element("config:config-item")
        element72.add_param("config:name", "ConsiderTextWrapOnObjPos")
        element72.add_param("config:type", "boolean")
        element25.add_content(element72)
        element72.set_value("false")
        element73 = XML.Element("config:config-item")
        element73.add_param("config:name", "TableRowKeep")
        element73.add_param("config:type", "boolean")
        element25.add_content(element73)
        element73.set_value("false")
        element74 = XML.Element("config:config-item")
        element74.add_param("config:name", "TabsRelativeToIndent")
        element74.add_param("config:type", "boolean")
        element25.add_content(element74)
        element74.set_value("false")
        element75 = XML.Element("config:config-item")
        element75.add_param("config:name", "IgnoreTabsAndBlanksForLineCalculation")
        element75.add_param("config:type", "boolean")
        element25.add_content(element75)
        element75.set_value("false")
        element76 = XML.Element("config:config-item")
        element76.add_param("config:name", "RsidRoot")
        element76.add_param("config:type", "int")
        element25.add_content(element76)
        element76.set_value("0")
        element77 = XML.Element("config:config-item")
        element77.add_param("config:name", "LoadReadonly")
        element77.add_param("config:type", "boolean")
        element25.add_content(element77)
        element77.set_value("false")
        element78 = XML.Element("config:config-item")
        element78.add_param("config:name", "ClipAsCharacterAnchoredWriterFlyFrames")
        element78.add_param("config:type", "boolean")
        element25.add_content(element78)
        element78.set_value("false")
        element79 = XML.Element("config:config-item")
        element79.add_param("config:name", "UnxForceZeroExtLeading")
        element79.add_param("config:type", "boolean")
        element25.add_content(element79)
        element79.set_value("false")
        element80 = XML.Element("config:config-item")
        element80.add_param("config:name", "UseOldPrinterMetrics")
        element80.add_param("config:type", "boolean")
        element25.add_content(element80)
        element80.set_value("false")
        element81 = XML.Element("config:config-item")
        element81.add_param("config:name", "TabAtLeftIndentForParagraphsInList")
        element81.add_param("config:type", "boolean")
        element25.add_content(element81)
        element81.set_value("false")
        element82 = XML.Element("config:config-item")
        element82.add_param("config:name", "Rsid")
        element82.add_param("config:type", "int")
        element25.add_content(element82)
        element82.set_value("126673")
        element83 = XML.Element("config:config-item")
        element83.add_param("config:name", "MsWordCompTrailingBlanks")
        element83.add_param("config:type", "boolean")
        element25.add_content(element83)
        element83.set_value("false")
        element84 = XML.Element("config:config-item")
        element84.add_param("config:name", "MathBaselineAlignment")
        element84.add_param("config:type", "boolean")
        element25.add_content(element84)
        element84.set_value("false")
        element85 = XML.Element("config:config-item")
        element85.add_param("config:name", "InvertBorderSpacing")
        element85.add_param("config:type", "boolean")
        element25.add_content(element85)
        element85.set_value("false")
        element86 = XML.Element("config:config-item")
        element86.add_param("config:name", "CollapseEmptyCellPara")
        element86.add_param("config:type", "boolean")
        element25.add_content(element86)
        element86.set_value("false")
        element87 = XML.Element("config:config-item")
        element87.add_param("config:name", "TabOverflow")
        element87.add_param("config:type", "boolean")
        element25.add_content(element87)
        element87.set_value("false")
        element88 = XML.Element("config:config-item")
        element88.add_param("config:name", "StylesNoDefault")
        element88.add_param("config:type", "boolean")
        element25.add_content(element88)
        element88.set_value("false")
        element89 = XML.Element("config:config-item")
        element89.add_param("config:name", "ClippedPictures")
        element89.add_param("config:type", "boolean")
        element25.add_content(element89)
        element89.set_value("false")
        element90 = XML.Element("config:config-item")
        element90.add_param("config:name", "EmbedFonts")
        element90.add_param("config:type", "boolean")
        element25.add_content(element90)
        element90.set_value("false")
        element91 = XML.Element("config:config-item")
        element91.add_param("config:name", "EmbedOnlyUsedFonts")
        element91.add_param("config:type", "boolean")
        element25.add_content(element91)
        element91.set_value("false")
        element92 = XML.Element("config:config-item")
        element92.add_param("config:name", "EmbedLatinScriptFonts")
        element92.add_param("config:type", "boolean")
        element25.add_content(element92)
        element92.set_value("false")
        element93 = XML.Element("config:config-item")
        element93.add_param("config:name", "EmbedAsianScriptFonts")
        element93.add_param("config:type", "boolean")
        element25.add_content(element93)
        element93.set_value("false")
        element94 = XML.Element("config:config-item")
        element94.add_param("config:name", "EmptyDbFieldHidesPara")
        element94.add_param("config:type", "boolean")
        element25.add_content(element94)
        element94.set_value("false")
        element95 = XML.Element("config:config-item")
        element95.add_param("config:name", "EmbedComplexScriptFonts")
        element95.add_param("config:type", "boolean")
        element25.add_content(element95)
        element95.set_value("false")
        element96 = XML.Element("config:config-item")
        element96.add_param("config:name", "TabOverMargin")
        element96.add_param("config:type", "boolean")
        element25.add_content(element96)
        element96.set_value("false")
        element97 = XML.Element("config:config-item")
        element97.add_param("config:name", "TabOverSpacing")
        element97.add_param("config:type", "boolean")
        element25.add_content(element97)
        element97.set_value("false")
        element98 = XML.Element("config:config-item")
        element98.add_param("config:name", "TreatSingleColumnBreakAsPageBreak")
        element98.add_param("config:type", "boolean")
        element25.add_content(element98)
        element98.set_value("false")
        element99 = XML.Element("config:config-item")
        element99.add_param("config:name", "SurroundTextWrapSmall")
        element99.add_param("config:type", "boolean")
        element25.add_content(element99)
        element99.set_value("false")
        element100 = XML.Element("config:config-item")
        element100.add_param("config:name", "ApplyParagraphMarkFormatToNumbering")
        element100.add_param("config:type", "boolean")
        element25.add_content(element100)
        element100.set_value("false")
        element101 = XML.Element("config:config-item")
        element101.add_param("config:name", "PropLineSpacingShrinksFirstLine")
        element101.add_param("config:type", "boolean")
        element25.add_content(element101)
        element101.set_value("false")
        element102 = XML.Element("config:config-item")
        element102.add_param("config:name", "SubtractFlysAnchoredAtFlys")
        element102.add_param("config:type", "boolean")
        element25.add_content(element102)
        element102.set_value("false")
        element103 = XML.Element("config:config-item")
        element103.add_param("config:name", "DisableOffPagePositioning")
        element103.add_param("config:type", "boolean")
        element25.add_content(element103)
        element103.set_value("false")
        element104 = XML.Element("config:config-item")
        element104.add_param("config:name", "ContinuousEndnotes")
        element104.add_param("config:type", "boolean")
        element25.add_content(element104)
        element104.set_value("false")
        element105 = XML.Element("config:config-item")
        element105.add_param("config:name", "ProtectBookmarks")
        element105.add_param("config:type", "boolean")
        element25.add_content(element105)
        element105.set_value("false")
        element106 = XML.Element("config:config-item")
        element106.add_param("config:name", "ProtectFields")
        element106.add_param("config:type", "boolean")
        element25.add_content(element106)
        element106.set_value("false")
        element107 = XML.Element("config:config-item")
        element107.add_param("config:name", "HeaderSpacingBelowLastPara")
        element107.add_param("config:type", "boolean")
        element25.add_content(element107)
        element107.set_value("false")
        element108 = XML.Element("config:config-item")
        element108.add_param("config:name", "FrameAutowidthWithMorePara")
        element108.add_param("config:type", "boolean")
        element25.add_content(element108)
        element108.set_value("false")
        element109 = XML.Element("config:config-item")
        element109.add_param("config:name", "GutterAtTop")
        element109.add_param("config:type", "boolean")
        element25.add_content(element109)
        element109.set_value("false")
        element110 = XML.Element("config:config-item")
        element110.add_param("config:name", "PrintAnnotationMode")
        element110.add_param("config:type", "short")
        element25.add_content(element110)
        element110.set_value("0")
        element111 = XML.Element("config:config-item")
        element111.add_param("config:name", "PrintGraphics")
        element111.add_param("config:type", "boolean")
        element25.add_content(element111)
        element111.set_value("false")
        element112 = XML.Element("config:config-item")
        element112.add_param("config:name", "PrintBlackFonts")
        element112.add_param("config:type", "boolean")
        element25.add_content(element112)
        element112.set_value("false")
        element113 = XML.Element("config:config-item")
        element113.add_param("config:name", "PrintLeftPages")
        element113.add_param("config:type", "boolean")
        element25.add_content(element113)
        element113.set_value("false")
        element114 = XML.Element("config:config-item")
        element114.add_param("config:name", "PrintControls")
        element114.add_param("config:type", "boolean")
        element25.add_content(element114)
        element114.set_value("false")
        element115 = XML.Element("config:config-item")
        element115.add_param("config:name", "PrintPageBackground")
        element115.add_param("config:type", "boolean")
        element25.add_content(element115)
        element115.set_value("false")
        element116 = XML.Element("config:config-item")
        element116.add_param("config:name", "PrintTextPlaceholder")
        element116.add_param("config:type", "boolean")
        element25.add_content(element116)
        element116.set_value("false")
        element117 = XML.Element("config:config-item")
        element117.add_param("config:name", "PrintDrawings")
        element117.add_param("config:type", "boolean")
        element25.add_content(element117)
        element117.set_value("false")
        element118 = XML.Element("config:config-item")
        element118.add_param("config:name", "PrintHiddenText")
        element118.add_param("config:type", "boolean")
        element25.add_content(element118)
        element118.set_value("false")
        element119 = XML.Element("config:config-item")
        element119.add_param("config:name", "PrintProspect")
        element119.add_param("config:type", "boolean")
        element25.add_content(element119)
        element119.set_value("false")
        element120 = XML.Element("config:config-item")
        element120.add_param("config:name", "PrintTables")
        element120.add_param("config:type", "boolean")
        element25.add_content(element120)
        element120.set_value("false")
        element121 = XML.Element("config:config-item")
        element121.add_param("config:name", "PrintProspectRTL")
        element121.add_param("config:type", "boolean")
        element25.add_content(element121)
        element121.set_value("false")
        element122 = XML.Element("config:config-item")
        element122.add_param("config:name", "PrintReversed")
        element122.add_param("config:type", "boolean")
        element25.add_content(element122)
        element122.set_value("false")
        element123 = XML.Element("config:config-item")
        element123.add_param("config:name", "PrintRightPages")
        element123.add_param("config:type", "boolean")
        element25.add_content(element123)
        element123.set_value("false")
        element124 = XML.Element("config:config-item")
        element124.add_param("config:name", "PrintFaxName")
        element124.add_param("config:type", "string")
        element25.add_content(element124)
        element125 = XML.Element("config:config-item")
        element125.add_param("config:name", "PrintPaperFromSetup")
        element125.add_param("config:type", "boolean")
        element25.add_content(element125)
        element125.set_value("false")
        element126 = XML.Element("config:config-item")
        element126.add_param("config:name", "PrintEmptyPages")
        element126.add_param("config:type", "boolean")
        element25.add_content(element126)
        element126.set_value("false")

    def run(self, folder):
        path = Util.opj(folder, "settings.xml")
        self.save(path)
